<?php

/**
 * @file Contains afrikaburn incident module.
 */

/**
 * Implements hook_form_FORM_ID_alter()
 * Prepopulates type from URL
 */
function afrikaburn_incident_form_node_incident_form_alter(&$form, &$form_state){

  $types = explode(',', \Drupal::request()->get('types'));
  foreach($types as $index=>$type){
    $form['field_incident_type']['widget'][$index] = $form['field_incident_type']['widget'][0];
    $form['field_incident_type']['widget'][$index]['target_id']['#default_value'] = \Drupal\taxonomy\Entity\Term::load($type);
  }

  $new_state = \Drupal::request()->get('newstate');
  if ($new_state) {
    $form['field_incident_state']['widget']['#default_value'] = $new_state;
    $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($new_state);
    $form['field_description']['widget'][0]['value']['#default_value'] = 'Changing state to ' . $term->name->value;
  }

  $form['actions'][] = [
    '#type' => 'markup',
    '#markup' => '<a class="button" href="/wrangle/incidents">Cancel</a>',
    '#weight' => 100,
  ];

  $form['#action'] == '/node/add/incident';

  $form['advanced']['#access'] = FALSE;
  $form['actions']['submit']['#submit'][] = 'afrikaburn_incident_submit';
}

/**
 * Implements hook_theme().
 * Views Customizaton.
 */
function afrikaburn_incident_theme(){
  return [
    'views_view__wrangle_incidents' => [
      'template' => 'views-view--wrangle',
      'base hook' => 'view',
    ],
    'views_view_table__wrangle_incidents' => [
      'template' => 'views-view-table--wrangle-incidents',
      'base hook' => 'view',
    ],
    'views_view_excel_export__wrangle_incidents' => [
      'base hook' => 'view',
    ],
  ];
}

/**
 * Implements hook_preprocess_views_view().
 */
function afrikaburn_incident_preprocess_views_view(&$variables){
  switch ($variables['id']){
    case 'wrangle_incidents':
      $variables['#attached']['library'][] = 'afrikaburn_incident/log';
      $variables['#attached']['library'][] = 'afrikaburn_shared/log';
    break;
  }
}


/**
 * Implements hook_preprocess_views_view_fields().
 */
function afrikaburn_incident_preprocess_views_view_fields(&$variables) {
  if ($variables['view']->id() == 'wrangle_incidents' && $variables['view']->current_display == 'excel_export'){

  }
}


/**
 * Redirect incident submit to incident view
 */
function afrikaburn_incident_submit($form, $form_state){

  $values = $form_state->getValues();
  $properties = [
    'vid' => 'incident_type',
    'name' => 'State change'
  ];
  $state_changer = array_shift(
    \Drupal::entityManager()
      ->getStorage('taxonomy_term')
      ->loadByProperties($properties)
  );
  $state_change = in_array($state_changer->tid->value,
    array_column(
      $values['field_incident_type'], 'target_id'
    )
  );
  $new_state = array_shift(
    array_column(
      $values['field_incident_state'], 'target_id'
    )
  );
  $related = array_column(
    $values['field_related_incident'], 'target_id'
  );

  if ($state_change && $related) {
    $targets = \Drupal::entityTypeManager()
      ->getStorage('node')
      ->load($related);
    foreach($targets as $target){
      $target->set('field_incident_state', [['target_id' =>$new_state]]);
      $target->save();
    }
  }

  $url = \Drupal\Core\Url::fromUri('internal:/wrangle/incidents');
  $form_state->setRedirectUrl($url);
}

