<?php


/**
 * Implements hook_form_FOMR_ID_alter().
 */
function afrikaburn_registration_form_user_form_alter(&$form, $form_state, $form_id){

  // Add JS and CSS libraries
  $form['#attached']['library'][] = 'afrikaburn_registration/afrikaburn_registration';
  $form['#attached']['library'][] = 'afrikaburn_shared/afrikaburn_wizard';

  // Hide submit while loading
  $form['actions']['#attributes']['class'][] = 'hidden';

  // Fix gender validation
  $options = &$form['field_gender']['widget']['#options'];
  if (array_key_exists( '_none', $options)) {
    $keys = array_keys($options);
    $keys[0] = '';
    $options = array_combine( $keys, $options);
  }

  // Hide email retype on user create
  $form['field_email_retype']['#access'] = \Drupal::currentUser()->isAnonymous();

  // Add ID, email validation
  if (in_array($form_id, ['user_form', 'user_register_form'])) {
    $form['#validate'][] = 'afrikaburn_registration_user_id_validate';
    if (\Drupal::currentUser()->isAnonymous()) $form['#validate'][] = 'afrikaburn_registration_mail_validate';
  }

  // Add quicket handlers
  switch ($form_id){
    case 'user_form': $form['actions']['submit']['#submit'][] = 'afrikaburn_registration_update_quicket'; break;
    case 'user_register_form': $form['actions']['submit']['#submit'][] = 'afrikaburn_registration_new_quicket'; break;
  }
}


/* ---- Validators ---- */


/**
 * ID number validation
 */
function afrikaburn_registration_user_id_validate($form, &$form_state) {

  $id = $form_state->getValue('field_id_number')[0]['value'];
  if (isset($id)) {

    if (!preg_match('/^[a-zA-Z0-9]+$/', $id)){
      $form_state->setErrorByName('field_id_number', t('Only numbers and letters are allowed.'));
    }

    if ($user = $form_state->getFormObject()->getEntity()){

      $existing = db_query(
        '
          SELECT COUNT(entity_id)
          FROM {user__field_id_number}
          WHERE entity_id != :uid AND field_id_number_value = :id
        ',
        [
          ':uid' => $user->id(),
          ':id' => $id,
        ]
      )->fetchField();

      if ($existing) {
        $form_state->setErrorByName('field_id_number', t('This number is already in use.'));
      }

    } else {

      $existing = db_query(
        '
          SELECT COUNT(entity_id)
          FROM {user__field_id_number}
          WHERE field_id_number_value = :id
        ',
        [
          ':id' => $form_state->getValue('field_id_number')[0]['value'],
        ]
      )->fetchField();

      if ($existing) {
        $form_state->setErrorByName('field_id_number', t('This number is already in use.'));
      }

    }
  }
}

/**
 * Email retype validation
 */
function afrikaburn_registration_mail_validate($form, &$form_state) {

  $mail = $form_state->getValue('mail');
  $retype = $form_state->getValue('field_email_retype')[0]['value'];

  if ($mail != $retype) {
    $form_state->setErrorByName('mail', t('Email address and Retype Email address should match!'));
    $form_state->setErrorByName('field_email_retype', t('Email address and Retype Email address should match!'));
  }
}


/* ---- Quicket handlers ---- */


/**
 * User registration form.
 */
function afrikaburn_registration_new_quicket($form, &$form_state) {

  $values = $form_state->getValues();
  $user = \Drupal\user\Entity\User::load($form_state->getValues()['uid']);

  module_load_include('inc', 'afrikaburn_registration', 'includes/quicket');
  $quicket = _quicket(
    'POST',
    isset($values['field_id_number']) ? $values['field_id_number'][0]['value']: NULL,
    isset($values['field_teens']) ? $values['field_teens'][0]['value']: 0,
    isset($values['field_kids']) ? $values['field_kids'][0]['value'] : 0
  );

  $user->field_quicket_code = $quicket['code'];
  $user->field_quicket_id = $quicket['id'];
  $user->save();
}

/**
 * User edit submission handler.
 */
function afrikaburn_registration_update_quicket($form, &$form_state) {

  $values = $form_state->getValues();
  $user = \Drupal\user\Entity\User::load($form_state->getValues()['uid']);
  $quicket_id = $user->get('field_quicket_id')->getValue()[0]['value'];

  $new = [
    'id' => isset($values['field_id_number']) ? $values['field_id_number'][0]['value']: 0,
    'teens' => isset($values['field_teens']) ? $values['field_teens'][0]['value']: 0,
    'kids' => isset($values['field_kids']) ? $values['field_kids'][0]['value'] : 0,
  ];

  module_load_include('inc', 'afrikaburn_registration', 'includes/quicket');
  $quicket = _quicket(
    'PUT',
    $new['id'],
    $new['teens'],
    $new['kids'],
    $quicket_id
  );

  if (!$quicket) {
    $quicket = _quicket(
      'POST',
      $new['id'],
      $new['teens'],
      $new['kids']
    );
  }

  $user->field_quicket_code = $quicket['code'];
  $user->field_quicket_id = $quicket['id'];
  $user->save();
}
