<?php

/**
 * @file
 * Contains Afrikaburn Crew module.
 */


/* ----- Theme hooks ----- */


/**
 * Implements hook_theme().
 * Views Customizaton.
 */
function afrikaburn_crew_theme(){
  return [
    'views_view__wrangle_dpw' => [
      'template' => 'views-view--wrangle',
      'base hook' => 'view',
    ],
    'views_view_table__wrangle_dpw' => [
      'template' => 'views-view-table--wrangle-crew',
      'base hook' => 'view',
    ],

    'views_view__wrangle_sanctuary' => [
      'template' => 'views-view--wrangle',
      'base hook' => 'view',
    ],
    'views_view_table__wrangle_sanctuary' => [
      'template' => 'views-view-table--wrangle-crew',
      'base hook' => 'view',
    ],
  ];
}


/* ----- Preprocessing hooks ----- */


/**
 * Implements hook_preprocess_views_view().
 */
function afrikaburn_crew_preprocess_views_view(&$variables){

  $year = (int)$variables['display_id'];

  switch ($variables['id']){
    case 'wrangle_dpw':
    case 'wrangle_sanctuary':
      if ($year >= 2019) {
        $variables['#attached']['library'][] = 'afrikaburn_crew/wrangle';
        module_load_include('inc', 'afrikaburn_crew', 'includes/wrangle.crew');
        _prepare_wrangler_view($variables);
      }
    break;
  }
}

// /**
//  * Implements hook_preprocess_views_view_table().
//  */
function afrikaburn_crew_preprocess_views_view_table(&$variables) {

  $year = (int)$variables['view']->current_display;

  switch ($variables['view']->id()){
    case 'wrangle_dpw':
    case 'wrangle_sanctuary':
      if ($year >= 2019) {
        module_load_include('inc', 'afrikaburn_crew', 'includes/wrangle.crew');
        _insert_wrangler_view_rows($variables);
      }
    break;
  }
}