<?php

/**
 * @file
 * Contains Afrikaburn Crew module.
 */


/* ----- Theme hooks ----- */


/**
 * Implements hook_theme().
 * Views Customizaton.
 */
function afrikaburn_application_theme(){
  return [
    'views_view__wrangle_subsidised' => [
      'template' => 'views-view--wrangle',
      'base hook' => 'view',
    ],
    'views_view_table__wrangle_subsidised' => [
      'template' => 'views-view-table--wrangle-application',
      'base hook' => 'view',
    ],
    'views_view__wrangle_community_tna' => [
      'template' => 'views-view--wrangle',
      'base hook' => 'view',
    ],
    'views_view_table__wrangle_community_tna' => [
      'template' => 'views-view-table--wrangle-application',
      'base hook' => 'view',
    ],
  ];
}


/* ----- Preprocessing hooks ----- */


/**
 * Implements hook_preprocess_views_view().
 */
function afrikaburn_application_preprocess_views_view(&$variables){

  $year = (int)$variables['display_id'];

  switch ($variables['id']){
    case 'wrangle_community_tna':
    case 'wrangle_subsidised':
      if ($year >= 2019) {
        $variables['#attached']['library'][] = 'afrikaburn_application/wrangle';
        module_load_include('inc', 'afrikaburn_application', 'includes/wrangle.application');
        _prepare_wrangler_view($variables);
      }
    break;
  }
}

/**
 * Implements hook_preprocess_views_view_table().
 */
function afrikaburn_application_preprocess_views_view_table(&$variables) {

  $year = (int)$variables['view']->current_display;

  switch ($variables['view']->id()){
    case 'wrangle_community_tna':
    case 'wrangle_subsidised':
      if ($year >= 2019) {
        module_load_include('inc', 'afrikaburn_application', 'includes/wrangle.application');
        _insert_wrangler_view_rows($variables);
      }
    break;
  }
}


/* ----- Form alters ----- */


/**
 * Implements hook_form_FORM_ID_alter().
 * Alters dashboard filter form.
 */
function afrikaburn_application_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  $form['#after_build'][] = 'afrikaburn_application_after_build';
}


/**
 * Adds filter options
 */
function afrikaburn_application_after_build($form, $form_state) {
  $view = $form_state->getStorage('view')['view'];
  if ($view->storage->get('id') == 'wrangle_subsidised'){
    $form['status']['#options']['All'] = '- any review state -';
    $form['wrangler']['#options'] =
      [
        'All' => t('- any wrangler -'),
      ] + $form['wrangler']['#options'];
  }
  return $form;
}