subsidised.stats:
  route_name: afrikaburn_application.wrangle.subsidised
  title: Stats
  base_route: afrikaburn_application.wrangle.subsidised
subsidised.2019:
  route_name: afrikaburn_application.wrangle.subsidised-2019
  title: "2019"
  base_route: afrikaburn_application.wrangle.subsidised
subsidised.2018:
  route_name: afrikaburn_application.wrangle.subsidised-2018
  title: "2018"
  base_route: afrikaburn_application.wrangle.subsidised
