subsidised.stats:
  route_name: afrikaburn_application.wrangle.subsidised
  title: Stats
  base_route: afrikaburn_application.wrangle.subsidised
subsidised.2020:
  route_name: afrikaburn_application.wrangle.subsidised-2020
  title: "2020"
  base_route: afrikaburn_application.wrangle.subsidised
subsidised.2019:
  route_name: afrikaburn_application.wrangle.subsidised-2019
  title: "2019"
  base_route: afrikaburn_application.wrangle.subsidised
subsidised.2018:
  route_name: afrikaburn_application.wrangle.subsidised-2018
  title: "2018"
  base_route: afrikaburn_application.wrangle.subsidised

anathi.stats:
  route_name: afrikaburn_application.wrangle.anathi
  title: Stats
  base_route: afrikaburn_application.wrangle.anathi
anathi.2019:
  route_name: afrikaburn_application.wrangle.anathi-2019
  title: "2019"
  base_route: afrikaburn_application.wrangle.anathi
anathi.2018:
  route_name: afrikaburn_application.wrangle.anathi-2018
  title: "2018"
  base_route: afrikaburn_application.wrangle.anathi