<?php

/**
 * @file
 * Contains Afrikaburn alert module.
 */


/* ----- Module Hooks ----- */


/**
 * Implements hook_page_attachments().
 * Attach bio libraries.
 */
function afrikaburn_alert_page_attachments(&$page) {
  $page['#attached']['library'][] = 'afrikaburn_alert/alert';
}

/**
 * Implements hook_theme().
 */
function afrikaburn_alert_theme() {
  return [
    'views_view_fields__alerts' => [
      'template' => 'views-view-fields--alerts',
      'base hook' => 'view',
    ],
  ];
}


/* ----- Entity Hooks ----- */


/**
 * Implements hook_ENTITY_TYPE_insert.
 */
function afrikaburn_alert_node_insert($entity){
  module_load_include('inc', 'afrikaburn_alert', 'includes/alert');
  module_load_include('inc', 'afrikaburn_notification', 'includes/collective');

  $bundle = $entity->bundle();
  if (in_array($bundle, ['art', 'performances', 'mutant_vehicles', 'theme_camps'])){

    $collective = @array_shift(
      array_filter(
        [
          $entity->field_collective->entity,
          $entity->field_collective->getEntity(),
        ]
      )
    );

    if (
      preg_match('/^\/registration\/update/', \Drupal::service('path.current')->getPath()) ||
      !_diff($entity)
    ) return;

    _alert(
      'create',
      $collective,
      $entity
    );
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert.
 */
function afrikaburn_alert_comment_insert($entity){
  module_load_include('inc', 'afrikaburn_alert', 'includes/alert');

  $bundle = $entity->bundle();

  if (in_array($bundle, ['post', 'comment'])){
    _alert(
      $bundle,
      $entity->getCommentedEntity(),
      $entity
    );
  }
}

/**
 * Implements hook_ENTITY_TYPE_update.
 */
function afrikaburn_alert_node_update($entity){
  module_load_include('inc', 'afrikaburn_alert', 'includes/alert');

  $bundle = $entity->bundle();

  if (in_array($bundle, ['art', 'performances', 'mutant_vehicles', 'theme_camps'])){

    $collective = @array_shift(
      array_filter(
        [
          $entity->field_collective->entity,
          $entity->field_collective->getEntity(),
        ]
      )
    );

    _alert(
      'update',
      $collective,
      $entity
    );
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete.
 */
function afrikaburn_alert_node_predelete($entity){
  module_load_include('inc', 'afrikaburn_alert', 'includes/alert');

  $bundle = $entity->bundle();

  if (in_array($bundle, ['art', 'performances', 'mutant_vehicles', 'theme_camps'])){

    $collective = @array_shift(
      array_filter(
        [
          $entity->field_collective->entity,
          $entity->field_collective->getEntity(),
        ]
      )
    );

    _alert(
      'delete',
      $collective,
      $entity
    );
  }
}

