<?php

/**
 * @file.
 */

use \Drupal\user\Entity\User;


/**
 * Implements hook_ENTITY_TYPE_update.
 */
function afrikaburn_notification_node_update($entity){

  $bundle = $entity->bundle();

  if (in_array($bundle, ['art', 'performances', 'mutant_vehicles', 'theme_camps'])){

    module_load_include('inc', 'afrikaburn_notification', 'includes/email');

    $user = User::load(\Drupal::currentUser()->id());
    $stage = $entity->get('field_form_mode')->value;
    $complete = array_column($entity->get('field_prjr_complete')->getValue(), 'value');
    $state = in_array($stage, $complete) ? 'update' : 'new';
    $settings = \Drupal::config('afrikaburn_notification.settings');
    $collective = _afrikaburn_notification_collective($entity);

    $address = [
      'to' => [
        'collective' => $collective['title'] . '<shared@afrikaburn.com>',
        'wranglers' => $settings->get($bundle . '-wranglers'),
      ],
      'from' => [
        'collective' => $settings->get($bundle . '-wranglers'),
        'wranglers' =>
          $user->field_first_name->value .
          '"' . $user->name . '"' .
          $user->field_last_name->value . ' via AfrikaBurn Tribe' .
          '<' . $user->field_display_mail->value . '>',
      ],
      'bcc' => [
        'collective' => $collective['members'],
        'wranglers' => NULL,
      ],
    ];

    foreach(['collective', 'wranglers'] as $recipient){
      $result = \Drupal::service('plugin.manager.mail')->mail(
        'afrikaburn_notification',
        $state . '_project_registration',
        $address['to'][$recipient],
        \Drupal::currentUser()->getPreferredLangcode(),
        [
          'from' => $address['from'][$recipient],
          'subject' => $settings->get(
            implode('-', [$bundle, $stage, $state, $recipient, 'subject'])
          ),
          'message' => $settings->get(
            implode('-', [$bundle, $stage, $state, $recipient, 'body'])
          ),
          'bcc' => $address['bcc'][$recipient],
          'node' => $entity,
        ],
        $address['from'][$recipient],
        TRUE
      );
    }
  }
}


/**
 * Implements hook_mail().
 */
function afrikaburn_notification_mail($key, &$message, $params) {

  module_load_include('inc', 'afrikaburn_notification', 'includes/email');

  $node = $params['node'];
  $bundle = $node ? $node->bundle() : FALSE;

  if (in_array($bundle, ['art', 'mutant_vehicles', 'performances', 'theme_camps'])){

    $user = User::load(\Drupal::currentUser()->id());
    $tokens = ['node' => $node, 'user' => $user];

    $subject = $params['subject'];
    $message['body'] = [];
    $body = $params['message'];

    _afrikaburn_notification_entity_render($node, $body);
    _afrikaburn_notification_entity_diff($node, $body);
    _afrikaburn_notification_email_images($message, $body);

    $body = \Drupal::token()->replace($body, $tokens, ['clear' => true]);
    $subject = \Drupal::token()->replace($subject, $tokens, ['clear' => true]);

    $message['headers']['From'] = 'AfrikaBurn Tribe';
    $message['headers']['Reply-to'] = $params['from'];
    $message['headers']['Return-Path'] = $params['from'];
    $message['headers']['bcc'] = $params['bcc'];
    $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';

    $message['subject'] = $subject;
    $message['body'][] = $body;
  }
}
