<?php

/**
 * @file
 * Contains Afrikaburn Shared module.
 */

use \Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use \Drupal\user\Entity\User;

/**
 * Implements hook_form_alter().
 */
function afrikaburn_collective_form_alter(&$form, $form_state, $form_id) {

  // On non-admin pages
  if (!\Drupal::service('router.admin_context')->isAdminRoute(\Drupal::routeMatch()->getRouteObject())) {
    module_load_include('inc', 'afrikaburn_collective', 'includes/form');

    // Get Registration and Collective if applicable
    list($registration, $registration_title) = _get_registration();
    list($collective, $collective_title) = _get_collective($registration);

    // Set titles and defaults
    static $user;
    $user = isset($user) ? $user : User::load(\Drupal::currentUser()->id());
    _set_registration_form_title($form, $form_id, $collective_title, $registration_title);
    _set_registration_form_defaults($form, $form_state, $form_id, $user, $collective);
    _set_collective_defaults($form, $form_id, $user);
  }

}

/**
 * Implements hook_views_pre_view().
 * Hooked to set collective on drop down view selects
 */
function afrikaburn_collective_views_pre_view(\Drupal\views\ViewExecutable $view, $display_id, &$args){
  if ($view->id() == 'collective_members' && $display_id == 'entity_reference_1'){
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node && $node->field_collective){
      $args[0] = $node->field_collective->first()->getValue()['target_id'];
    } else if ($cid = \Drupal::request()->query->get('field_collective')) {
      $args[0] = $cid;
    }
  }
}
